services:
  api:
    build: .
    ports:
      - 8000:8000

    # env_file:
    #   - ./.env
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_PASS_PREDEV=password
      - DB_HOST=localhost
      - DB_NAME=jlp
      - SECRET_KEY=f9c7deb65801fdfa6895b9fd8e7995618ba8c49670774cf8821a3debd28f42c3
      - NOMBRE_EMPRESA=Josh Le Presta
      - NOMBRE_ARCHIVO_CUENTA_EXCEL=estado_de_cuenta